#!/bin/sh
set -e

# Compile C kernel
gcc \
    -m64 \
    -ffreestanding \
    -fno-pie \
    -mno-red-zone \
    -fcf-protection=none \
    -fno-asynchronous-unwind-tables \
    -fno-unwind-tables \
    -O0 \
    -c kernel/main.c \
    -o kernel/main.o

ld \
    -m elf_x86_64 \
    -Ttext 0x100000 \
    -e main \
    --oformat binary \
    -o kernel/kernel.bin \
    kernel/main.o

rm kernel/main.o


# Compile stage 1
nasm -f bin boot/stage1.asm -o boot/stage1.bin

# Compile Stage 2
nasm -f bin boot/stage2.asm -o boot/stage2.bin

# Create disk image (12 MB)
dd if=/dev/zero of=disk.img bs=1048576 count=12

# Put Stage 1 in sector 0
dd if=boot/stage1.bin of=disk.img conv=notrunc

# Put Stage 2 in sector 1
dd if=boot/stage2.bin of=disk.img bs=512 seek=1 conv=notrunc

# Put kernel at 10.6 MB (sectors 21709 - 23756)
dd if=kernel/kernel.bin of=disk.img bs=512 seek=21709 conv=notrunc

# Run QEMU
if [ "$(uname)" = "Darwin" ]; then
    DISPLAY_ARGS="-display cocoa,zoom-to-fit=on"
else
    DISPLAY_ARGS="-display gtk,zoom-to-fit=on"
fi

qemu-system-x86_64 \
    -m 32M \
    -cpu qemu64 \
    -no-reboot \
    -no-shutdown \
    $DISPLAY_ARGS \
    -drive format=raw,file=disk.img,if=ide,index=0

# Clean up intermediate files
rm boot/stage1.bin
rm boot/stage2.bin
